### ISSUE TITLE
The passphrase notification for encrypted volume in Drives-Manager

### ISSUE THREAD

**Issue by HalinReno** [lestcape/Drives-Manager#10]
I created an encrypted partition on a second hard drive with LUKS but do not have it loading during boot as I don't need it and don't want it mounted while logged in all the time. When I click on the mount icon the volume, a notification comes down asking for a passphrase, but I cannot type in it. I have to go to Nemo and mount it that way which works.
![untitled](https://cloud.githubusercontent.com/assets/9020284/7552347/16c4e058-f664-11e4-91af-8dea0627cad3.jpg)

Using Linux Mint 17.1 w/Cinnamon 2.4.8

Not sure if this is a Drives-Manager or a Cinnamon issue. Any help would be appreciated.

**Comment by lestcape** [comment]
Hi, is pretty easy disable drives manager and see if is cinnamon who try to mount your volume. Anyway, drives manager have an option to automount the volumens and currenlty this option mount all volumes, but is not a default option, because who normally need to handle this is cinnamon, but thats nor occurs on ubuntu 14.04, and then i add this option (is not recommended that you used this option if cinnamon is working well and i will not improve this option, because really this option is an invention to fixed a cinnamon bug on ubuntu 14.04). To enable the option, first you need to disable the cinnamon option of automount voulmes, and then active the option to be handled by drives manager, so i supposed that you don't do this and is cinnamon who currenlty is try to automount your volume. Thats i think is not a bug, only a wrong cinnamon behavior, that can be requested as a feature request on the cinnamon page, but you need to test first what occurs when you disable drives manager.

Regards.

**Comment by HalinReno** [comment]
Thanks for the reply,

I've tried what you said and it was already setup that way. It seems 
that no matter what I have checked or unchecked, it's the same. I just 
can't type in the field asking for my passphrase. Anyway, it works fine 
in Nemo so I'll just use that. Using drives-manager would have been a 
lot more convenient, though. Still a great desklet. Thanks for making it.

-Hal

**Comment by lestcape** [comment]
@HalinReno could you please disable drives manager and test if your problem occurs or not? If is just Drives manager i can try to fix it, if is cinnamon, the cinnamon devs could find a way, but we need to know where the problem is first and then try to find a solution in the right plase.

Regards.

**Comment by HalinReno** [comment]
I have disabled drives-manager and nothing is different. When I click on 
the mount icon on drives-manager whether I have drives-manager mounting 
and opening or cinnamon mounting and opening, I still cannot type in the 
passphrase field. It looks like there is a cursor in it, but when I 
start typing, nothing happens. The only way I can get it to where I can 
enter in a passphrase is with Nemo. Thanks for your help. If you want, I 
can capture a video of me tying this.

-Hal

**Comment by lestcape** [comment]
If you want, open an issue on cinnamon about this, and then references what we talking here. Or if not, can i do that for you? Is more clear to me what happend now.
Regards.

**Comment by HalinReno** [comment]
I will report the bug with Linux Mint and will refer to our emails. It 
does seem to me that this would be an issue with notifications in 
Cinnamon. Thank you for your help and thanks for making a great Desklet.

-Hal

**Comment by lestcape** [comment]
All our mails are attached in github and are public, so you can add the link:
https://github.com/lestcape/Drives-Manager/issues/10

and i recommend you also not report this problem on linux mint, instead, you can use the directed way, the cinnamon dev page, that is also on github:
https://github.com/linuxmint/Cinnamon

just use same thing, open an issue:
https://github.com/linuxmint/Cinnamon/issues

Direct link to create one:
https://github.com/lestcape/Drives-Manager/issues/new

Regards.

Direct link to create one:
https://github.com/lestcape/Drives-Manager/issues/new

Regards.

**Comment by lestcape** [comment]
This desklet have not support for cinnamon anymore. Will be available in gnome shell in the future.
