### ISSUE TITLE
How to hide /boot/efi?

### ISSUE THREAD

**Issue by dtrunk90** [lestcape/Drives-Manager#11]
How to hide /boot/efi drive?
![bildschirmfoto vom 2015-09-18 09 34 14](https://cloud.githubusercontent.com/assets/636557/9954351/945f488c-5de8-11e5-9a0a-c88ab5b77994.png)

**Comment by lestcape** [comment]
There are no way to hide an specific volume, is just only for categories in settings, and speaking of drive, volume and mount point, this not special. So, the only way is create a filter where disable specific volumes.

If you want resolve it now, i think this is the way:

This is a hard mount point and is read from /etc/mtab, so you need to find if is your mount inside this for: https://github.com/lestcape/Drives-Manager/blob/master/drivesManager%40lestcape/desklet.js#L1904

Then check if ( this.mountsHard[_pos][1] == "/boot/efi") and only let execute the internal code of the "for" if is not.

**Comment by dtrunk90** [comment]
Can wait till a better solution is there. It's just a "Nice-to-have". Maybe there should be a builtin functionality which can do this. Just a list of possible drives which can be (un)checked if visible or something like that.

**Comment by lestcape** [comment]
The problem is that: This option is dynamically, as depend of your current drivers. Cinnamon settings won't allow dynamically objects in the settings, so the only way is simulate this process with a list with a separator, but this is not user friendly. I have this inconvenience with several things and i don't want provide this type of solution to the users... How cinnamon settings is build to be easy for programmers, this appear will not be changed soon and i begin to develop some external solutions.

One was try to create a new customizable cinnamon settings, and then try to included the solution inside the cinnamon settings, but this fail for compatibility reason with the cinnamon settings, when they change his code (and this is constantly).  https://github.com/lestcape/Cinnamon-Installer

Another idea is move the applets and desklets settings inside cjs, instead of the python site, and add more complex setting's object when the settings is displayed in this way and the statical ones just in cinnamon settings. Thats is why i create this:
https://github.com/lestcape/Color-Chooser

and i begin the development of this:
https://github.com/lestcape/File-Chooser

But when i finished to create this dialogs i need to create a settings with the ability to display all cinnamon settings componets and another components more complex. Then, i will add this as an extension to cinnamon and will be possible have a more advance settings directly where the applet or desklet are displayed, without need the cinnamon settings at all. This idea can be see in this oldest request:
https://github.com/linuxmint/Cinnamon/issues/4403

As you can see i finished the color dialog.

So, the point is this will take a lot of time to appear.

**Comment by dtrunk90** [comment]
Consider it as a feature request when you have time and if it's possible. ;-)

**Comment by lestcape** [comment]
Yes why not...

**Comment by lestcape** [comment]
I'm moving the desklet to gnome shell. I live to cinnamon.
